In [2]:
import numpy as np

In [5]:
#create an array 3 rows and 8 columns
a=np.ones((3,8))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
A=np.array([[2,3,5,6,7,8,9,8],[9,8,7,6,5,4,3,2],[4,5,6,7,4,3,4,6]])
print(A)

[[2 3 5 6 7 8 9 8]
 [9 8 7 6 5 4 3 2]
 [4 5 6 7 4 3 4 6]]


In [8]:
#random module is subpackage of numpy
#random.rand--(range is greater than zero and less than one)
b=np.random.rand(8,4)
print(b)

[[0.44924352 0.62863766 0.08906495 0.27681287]
 [0.40669724 0.12275134 0.18934136 0.8286734 ]
 [0.83024918 0.08376258 0.98160458 0.59660613]
 [0.24904537 0.80600232 0.71400572 0.72200456]
 [0.20883119 0.56715855 0.60731679 0.43247231]
 [0.6493664  0.43762509 0.29774376 0.03779359]
 [0.9512858  0.53064027 0.66588826 0.50489467]
 [0.84252582 0.73307206 0.95984995 0.81822072]]


In [28]:
B=np.arange(1,33).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [25]:
#splitting at required positions
np.vsplit(B,(2,6))     #splits at 2 and 6(from starting we count) and remaining rows also print
np.vsplit(B,4)    #SPLITS IN TO REQUIRED N UMBER OF PARTS

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [23]:
b=np.arange(1,33).reshape(4,8)
print(b)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [30]:
np.hsplit(B,4)      #SPLITS IN TO REQUIRED NUMBER OF PARTS HORIZONTALLY

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [29]:
np.hsplit(B,(2,6))     #splits first two columns and 6 columns(from starting) and remaining

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5,  6],
        [11, 12, 13, 14],
        [19, 20, 21, 22],
        [27, 28, 29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [32]:
#TRIGONOMETRY
np.pi

3.141592653589793

In [33]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [34]:
k=np.rad2deg(A)    #radian to degree conversion
print(k)

[ 45.  60.  90. 180.]


In [37]:
l=np.deg2rad(k)    #degree to radian conversion
print(l)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [38]:
np.sin(1)   #sin value


0.8414709848078965

In [39]:
np.cos(1)     #cos value


0.5403023058681398

In [40]:
np.tan(1)     #tan value

1.5574077246549023

In [43]:
c=np.array([23,45,67,89,21,34])
print(c)

[23 45 67 89 21 34]


In [44]:
#mean
np.mean(c)

46.5

In [45]:
np.median(c)   #median

39.5

In [48]:
np.std(c)    #standard

24.452334585202017

In [49]:
np.var(c)    #variance

597.9166666666666

In [50]:
n=np.arange(1,5).reshape(2,2)
print(n)

[[1 2]
 [3 4]]


In [51]:
np.linalg.inv(n)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [52]:
j=np.arange(1,25).reshape(6,4)
print(j)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [54]:
#INDEX OF MAXIMUM VALUE
np.argmax(j)   #gives index of maximum value(index starts from zero.so,max value 24 is present at 23 index position)

23

In [60]:
o=10*np.random.rand(20).reshape(5,4)
print(o)
np.argmax(o)

[[0.67293779 7.22195455 0.92114842 0.02354107]
 [2.81352203 9.73632993 4.36146027 7.01091413]
 [1.12759463 4.80693149 3.5877745  9.28010864]
 [3.37359921 1.74482333 4.33389183 2.04879076]
 [4.55753144 8.1128411  7.76242984 2.03349598]]


5

In [69]:
print(np.argmax(o,axis=0))   #gives index of max value along columns
print(np.argmin(o,axis=0))    #GIVE INDEX OF MIN VALUE ALONG COLUMNS

[4 1 4 2]
[0 3 0 0]


print(np.argmax(o,axis=1))    #gives index of max value along rows
print(np.argmin(o,axis=1))    #GIVE INDEX OF MIN VALUE ALONG ROWS

In [96]:
#using multiply function
a1=np.array([2,3,4,5,6,7])
a2=np.array([6,7,9,9,0,9])
np.multiply(a1,a2)   #multiplying two sorted arrays


array([12, 21, 36, 45,  0, 63])

In [97]:
a1=np.array([2,3,4,5,6,7])
a2=np.array([2,3,4,5,5,6])
np.divide(a1,a2)

array([1.        , 1.        , 1.        , 1.        , 1.2       ,
       1.16666667])

In [98]:
a1=np.array([2,3,4,5,6,7])
a2=np.array([9,8,7,6,5,4])
np.mod(a1,a2)

array([2, 3, 4, 5, 1, 3])

In [99]:
a1=np.array([2,3,4,5,6,7])
a2=np.array([9,8,7,6,5,4])
np.divmod(a1,a2)

(array([0, 0, 0, 0, 1, 1]), array([2, 3, 4, 5, 1, 3]))

In [100]:
np.log(1.2)        #natural log e

0.1823215567939546

In [101]:
np.log2(1.2)        #log base 2

0.2630344058337938

In [102]:
np.log10(1.2)      #log base 10

0.07918124604762482

In [105]:
b=np.array([5,6,7,10])
np.cumprod(b)    #gives multiplication of two values(5,5*6=30,30*7=210)

array([   5,   30,  210, 2100])